version: 1

formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
  file:
    class: logging.handlers.TimeRotatingFileHandler
    level: DEBUG
    formatter: default
    filename: /home/admin/projects/netinsight/log/app.log
    when: W6
    encoding: utf-8
    format: default
    backupCount: 30

loggers:
  app:
    handlers: [console, file]
    level: DEBUG

disable_exsiting_loggers: false
    